name: Daily ETL and Template Rendering Workflow

on:
  schedule:
    - cron: "45 1 * * *"

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  etl_pipeline:
    name: Run ETL Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ETL pipeline script
        run: python etl_pipeline.py
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

      - name: Commit changes
        run: |
          git config --global user.name "js"
          git config --global user.email "50718474+jarell-santella@users.noreply.github.com"
          git add db/csv
          git commit -m "chore(automated): add fetched daily data to csvs"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/jarell-santella/daily-top-songs-etl master

  render_templates:
    name: Render Templates
    needs: etl_pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest master
        run: |
          git config --global user.name "js"
          git config --global user.email "50718474+jarell-santella@users.noreply.github.com"
          git pull --rebase https://${{ secrets.GITHUB_TOKEN }}@github.com/jarell-santella/daily-top-songs-etl master

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run template rendering script
        run: python render_templates.py

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "chore(automated): update readme with daily data"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/jarell-santella/daily-top-songs-etl master
